name: "Record build and test results action"
author: "launchbleinc"
description: "Launchable action for recording build and test results"
branding:
  icon: 'circle'
  color: 'gray-dark'
inputs:
  build_name:
    required: false
    description: "The build name. Default GitHub SHA."
    default: $GITHUB_SHA
  max_days:
    required: false
    description: "The maximum number of days to collect commits retroactively. Default 30."
    default: "30"
  no_submodules:
    required: false
    description: "Stop collecting build information from Git Submodules. Default False."
    default: "false"
  no_build:
    required: false
    description: "Send test session without recording build. Default False."
    default: "false"
  python_version:
    required: false
    description: "Python version >= 3.5 <=3.10. Default 3.10"
    default: "3.10"
  report_path:
    required: true
    description: "The test report file path. Default ..."
    default: "."
  source_path:
    required: false
    description: "Path to a local Git repository/workspace. Default current directory."
    default: "."
  test_runner:
    required: true
    description: "test runner name"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - id: install
      shell: bash
      run: pip install "launchable>=1.56.1"
    - id: verify
      shell: bash
      run: |
        launchable verify
    - id: record_build
      shell: bash
      if: !inputs.no_build
      run: |
        if [ "${{ inputs.no_submodules }}" == 'false' ]; then
          launchable record build \
            --name ${{ inputs.build_name }} \
            --max-days ${{ inputs.max_days }} \
            --source src=${{ inputs.source_path }}
        else
          launchable record build \
            --name ${{ inputs.build_name }} \
            --max-days ${{ inputs.max_days }} \
            --source src=${{ inputs.source_path }} \
            --no-submodules
        fi
    - id: record_test
      shell: bash
      run: |
        if [ "${{ inputs.no_build }}" == 'false' ]; then
          launchable record tests \
            --build ${{ inputs.build_name }} \
            --allow-test-before-build \
            ${{ inputs.test_runner }} \
            ${{ inputs.report_path }}
        else
          launchable record tests \
            --build ${{ inputs.build_name }} \
            --allow-test-before-build \
            --no-build \
            ${{ inputs.test_runner }} \
            ${{ inputs.report_path }}
        fi
